package com.fast.xinyue.controller;

import com.fast.xinyue.domain.Request;
import com.fast.xinyue.repository.RequestRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.websocket.server.PathParam;
import java.util.List;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;




@RestController
@RequestMapping("/request")
public class RequestController {

    private Logger logger = LoggerFactory.getLogger(getClass());

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private RequestRepository requestRepository;

    @RequestMapping("/index")
    public String index(){
        return "index";
    }


    @RequestMapping(path = "/add",method = RequestMethod.POST)
    public List<Request> add(Request request){
        System.out.println("请求名称"+request.getRequestName());
        requestRepository.save(request);
        return requestRepository.findAll();
    }



    @RequestMapping("/Test")
    public String Test(@PathParam("username") String username, @PathParam("password") String password){
        logger.info("用户名称：{}",username);
        logger.info("用户密码：{}",password);
        return "success";
    }
}
