package com.fast.xinyue.controller;

import com.fast.xinyue.domain.Request;
import com.fast.xinyue.service.RequestService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


@Controller
@RequestMapping("/request")
public class RequestController {

    private Logger logger = LoggerFactory.getLogger(getClass());

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private RequestService requestService;


    @RequestMapping(path = "/add",method = RequestMethod.POST)
    public String add(Request request){
        logger.info("请求名称: {}",request.getRequestName());
        requestService.addRequest(request);
        return "redirect:/show/request";
    }
}
